server:
  port: 9527
spring:
  application:
    name: wisdomSite-zuul-gateway-dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka #服务注册地址
  instance:
    prefer-ip-address: true
zuul:
  routes:
    plat.serviceId: wisdomSite-plat #这是调用满足条件的服务名，注意要小写
    plat.path: /plat/** #这是所有路径前的通配
  ignored-services: "*" #用*来通配符，忽略从9527端口通过服务名来调用
  prefix: "/services" #这是所有路径的前缀
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
